### PR TITLE
Fixed the part to calculate `X` value.

### PR DESCRIPTION
**Pull request by Aniket-Pradhan**
Incremented the variable `i`, in for loop.

### CODE REVIEW

**Comment by Aniket-Pradhan** [comment]
Hello Dr. Alex.

I have replaced the variable `i` from the `for` loop using the `scanListIndex` value of the `triplet1`. That was a noob mistake. Probably I was in a hurry and missed that part. Now, the variable `i` doesn't come in the `for` loop, and in calculation of the `X` value.

Now, I had a query regarding the new test case. For that, shouldn't our `interpolationLeftSideX` be equal to 1.5? Because, we have the `halfHeight` as 500, `Y1` as 100, `Y2` as 900 and `step` as -1. This gives the `X` value as 1.5. On further calculating, we get `sigmaLeft` as ~2.12
The same goes for `sigmaRight`. We get `interpolationRightSideX` as 6.5 (`halfHeight = 500`, `Y1 = 100`, `Y2 = 900`, and `step = 1`), and again, we get the `sigmaRight` equal to 2.12.

If I am missing something, please do tell me. 😄

Thanks
Aniket Pradhan

**Comment by asmirn1** [comment]
H Aniket,

This is a good question. In the original version of the code, we used `i`-values as the first coordinate and `Intensity`-values as the second coordinate. However, the first coordinate should be `scanListIndex` because `scanListIndex` is an intrinsic property of a triplet and equal to the scan number in the raw data. When scan numbers go 1, 2, 3, ... without any gaps, it's possible to use either `i` or `scanListIndex` as the first coordinate and receive the same result. But in the test case we consider, you'll get different results. If you use `triplet1.scanListIndex` and `triplet2.scanListIndex` instead of `i` and `i - step`, you will get `interpolationLeftSideX = 6`

**Comment by Aniket-Pradhan** [comment]
Dear Dr. Alex,

I am unsure of the value of `intepolationLeftSideX`. Can you please explain how it comes out to be 6?

According to me, at the end of the `for` loop, we will have Triplet1 as the first triplet (`scanListIndex = 1`) and Triplet2 as the second triplet (`scanListIndex = 3`). This gives us the value of `interpolationLeftSideX = 1.5`. These values come because we are using `triplet1.scanListIndex` directly and not the variable `i`.

**Comment by asmirn1** [comment]
If my calculations are correct, then we have
`1 + (3 - 1) * (500 - 100) / (900 - 100)  = 2`

**Comment by Aniket-Pradhan** [comment]
Dear Dr. Alex

Your calculations are correct. I was using the wrong equation to find `X`. I have re-formed the equation in the code, using `index1` only.

Also, in the test-case, you were checking the value of `interpolationLeftSideX` instead of `sigmaLeft`. I have simply corrected the values of `sigmaLeft` and `sigmaRight` in the test case. 
We cannot directly check the values of `interpolationLeftSideX` in the test case, because `interpolationLeftSideX` is not a class variable.
Here, `interpolationLeftSideX = 2.0` and `sigmaLeft = interpolationLeftSideX / (2*log(2))^-1`

Thanks
Aniket :)

**Comment by asmirn1** [comment]
Thank you for correcting `sigmaLeft` and `sigmaRight`. I'll take a look.

**Comment by Aniket-Pradhan** [comment]
Dear Dr. Alex

Should we work on something else alongside we work on BiGaussian.java. If you could recommend me some new changes, or a new implementation, I would be happy to help.

Thanks
Aniket Pradhan

**Comment by asmirn1** [comment]
Hi Aniket,

Sorry for not replying you. I've been busy in a last few days. Unfortunately, I find it difficult to work on ADAP-3D right now.

However, you are welcome to continue contributing to ADAP-3D, and I'll try to help you with advice, but I won't have time to guide you through every detail as we did for the function `IntepolateX`.

The class `ContinuousWaveletTransform` performs wavelet transform of a signal and it's the slowest part of the algorithm. It would be very beneficial to speed up its calculations. Could you take a look at function `signalWaveletInnerProductOnePoint` of that class? Try to understand, how the algorithm works and see if you can improve its performance. For instance, I think that we can move the calculating of a wavelet (function `rickerWavelet`) outside the for-loop at line 509, which would speed up the overall calculations. 

Alex

**Comment by Aniket-Pradhan** [comment]
Sure. I'll try to come up with a few things of my own for the class ContinuousWaveletTransform.java.
If I stumble upon a problem, I will try to solve it on my own, and if I am unable to do it on my own, I will turn up to you. :)

**Pull request merged**
