### PR TITLE
Removed firstMzValue variable

### PR DESCRIPTION
**Pull request by Aniket-Pradhan**
We can use the `index1` variable instead of `firstMzValue`. Hence, `firstMzValue` is not needed.

### CODE REVIEW

**Comment by asmirn1** [comment]
Can we replace the code starting at line 136
```java
if (index1 >= 0) {
    ...
}
```
with the code
```java
if (index1 < 0)
    throw new IllegalArgumentException("Cannot find peak apex.");

...
```
I think it makes the code a little easier to read. Right now, we have so many if-statements and for-loops that it's painful to understand what's going on.

**Comment by asmirn1** [comment]
What's the meaning of `tempFlag`? It's confusing, and I would prefer to get rid of it. You use it in the code
```java
if (tempFlag != 0) {
    triplet1 = horizontalSlice.get(index1);
    if (triplet1.mz != roundedmz) {
        break;
    } else if (triplet1.scanListIndex - step != prevScanNumber) {
        continue;
    }
}
```
I agree that we need check `triplet1.mz == roundedMZ`. Can we put
```java
triplet1 = horizontalSlice.get(index1);
if (triplet1.mz != roundedmz) {
    break;
}
```
before `if (tempFlag != 0)`?

**Comment by Aniket-Pradhan** [comment]
Hello Dr. Alex,

The reason I have used tempFlag here is because, I am unsure whether the values of the scanListIndex have breaks or not. For example, if the values of scanListIndex of a slice are as follows:

| mz | scanListIndex |
|------|--------------------|
|10   |1|
|20|2|
|30|3|
|30|5|
|40|6|

And, our roundedmz is 30.

Then I think we need to check whether the `scanListIndex` of Triplet2 is equal to `scanListIndex - step` of Triplet1 - step. By Triplet2, I mean the Triplet just before Triplet1 in the sorted list - `horizontalSlice`.

For example, take a situation where the previous Triplet has an mz value of roundedmz, but the `scanListIndex` value is not the same as `scanListIndex - step` of Triplet1. According to the previous version of the code, I don't think that we require such values (intesities) for further processing, but still I am unsure whether the values of scanListIndex contains such breaks or not.

If the list doesn't contains such breaks, we can remove the whole part of tempFlag, the continue statements, and can simply check whether `Triplet.mz == roundedmz` or not.

**Comment by asmirn1** [comment]
Aniket,

I like that you are checking `scanListIndex` of the previous triplet, and `scanListIndex - step` of Triplet1. They should be equal but it's good that we are checking this equality.

I was asking about the meaning of `tempFlag`. As I understand, you use `tempFlag` to check if it's a first iteration (`tempFlag == 0`) or not a first iteration (`tempFlag != 0`). Can we skip that first iteration at all? Then, we could remove variable `tempFlag`. 

It seems that only the assignment `prevScanNumber = triplet1.scanListIndex` happens on the first iteration. Can you do that assignment and increase `index1` before the for-loop?

**Comment by Aniket-Pradhan** [comment]
Dear Dr. Alex,

I have made the necessary modifications. Even I was thinking of a better way to do this, but you just helped me there.

Thanks. :smile:

**Comment by asmirn1** [comment]
You are welcome! Eventually, we'll make this code much shorter and more clear. My next two comments:

*Comment 1*. You check the bounds of indices `i` and `index1` in two different places. First, in the for-loop at line 146
```java
for ( ; leftBound <= i && i <= rightBound; i += step, index1 += step) {
```
Second, in the if-statement at line 156
```java
if ((index1 == 0 && step < 0) || (index1 == horizontalSlice.size() - 1 && step > 0)) {
```
I think, it makes the code hard to understand. It's better to do both checks in one place. For instance, at line 146
```java
for (; leftBound <= i && i <= rightBound && 0 <= index1 && index1 < horizontalSlice.size();
          i += step, index1 += step) {
```
This way, you'll get rid of the if-statement at line 156.

*Comment 2*. I don't see anything bad in the case when `triplet1.scanListIndex - step != prevScanNumber` at line 151. Can you explain why you skip an iteration in this case?

**Comment by Aniket-Pradhan** [comment]
Hello Dr. Alex,

The `for` loop and the `if` conditions can be merged together, and so I have done.

For your second comment, as far as I have understood from the previous code, we need the Triplets with consecutive scanListIndex value. So, that is why we need to check whether `triplet1.scanListIndex - step != prevScanNumber`. However, I also saw that the statements 151 and 157 seem equivalent. Hence, I think that we can remove statement 157, and along with it, the variable `i`.
Please share your views on it.

Statement 151: `else if (triplet1.scanListIndex - step != prevScanNumber)`
Statement 157: `if (triplet2.scanListIndex != i - step)`

**Comment by asmirn1** [comment]
Hi Aniket,

I do think that the indices `i` and `index1` are somewhat redundant, so it would be nice to remove the variable `i`.

About the check `triplet1.scanListIndex - step == prevScanNumber`. Let's consider the case

|Index1| mz | Scan # | Intensity |
| ----- | --- | ------- | --------- |
| 1       | 40 | 1           | 100         |
| 2       | 40 | 3           | 900         |
| 3       | 40 | 4           | 1000      |
| 4       | 40 | 5           | 900         |
| 5       | 40 | 7           | 100         |

Let's say, we start from `index1 == 3` and descend to the left (i.e. `step = -1`). In this case, `halfHeight = 500`, and the loop should stop at `index1 == 1` because `100 < 500`. In this case, `triplet1` has to be the triplet from the first row (`index1 == 1`) and `triplet2` is the triplet from the second row (`index1 == 2`). Correspondingly, we should have `Y1 = 100` and `Y2 = 900`. Therefore, I think that we don't need check `triplet1.scanListIndex - step == prevScanNumber`.

This case is something that we didn't actually consider in the original version of the code since the scan numbers should go in sequence 1, 2, 3, ... without any gaps. But it's good that you noticed this case. We just need to make sure that the new code works if this case happens.

**Comment by Aniket-Pradhan** [comment]
Dear Dr. Alex,

I have removed the part with `prevScanNumber` and the variable `i`(mu) in the `for` loop. Instead, I have used `triplet1.scanListIndex - step` as a replacement to `i`. It will prevent any such case, as you said in your last comment. Please review the code, for this part.

Also, I had an idea, where we can remove the `index1` from the `for` loop as well. We could use an iterator. But, the problem is which one should be efficient? I feel that using `index1` would be more efficient, because if we use iterator, we will have to import a whole new class just for one iteration.

Thanks.
Aniket Pradhan

**Comment by asmirn1** [comment]
Hi Aniket,

Good work! Now the code looks much better. When I have time, I'll write a few tests for your code, and we'll discuss it further.

I don't think, there is much difference between using `index1` and an iterator. And it's better to keep the code simple.

Alex

**Comment by asmirn1** [comment]
Hi Aniket,

I've created a new JUnit test. It's in `msdk-featuredetection-adap3d/src/test/../algorithms/BiGaussianTest`, function `testInterpolationTest()`. It doesn't work now. Could you make it work?

Alex

**Comment by Aniket-Pradhan** [comment]
Hello Dr. Alex,

I looked into the JUnit test file, and saw that the command `importer.execute()` is not working correctly. It is not working for the file in the master branch as well. The output terminates at 
```
Feb 23, 2018 11:15:36 AM io.github.msdk.io.mzxml.MzXMLFileImportMethod execute
INFO: Started parsing file /home/themajor/Desktop/Chemistry_Stuff/msdk/msdk-featuredetection-adap3d/target/test-classes/tiny.mzXML
```
Are you facing the same issue as well? If yes, then I think we must figure out a workaround for `importer.execute()`. If not, can you help me in fixing this issue?

Aniket Pradhan

**Comment by asmirn1** [comment]
What error are you getting? Are you able to run tests `testgetBiGaussianValue()` and `testInterpolationX()`? Do you have file tiny.mzXML? 

I'm able to run the tests but they don't produce the expected results.

**Comment by Aniket-Pradhan** [comment]
Dear Dr. Alex,

I am getting no such error. The program/JUnit test terminates just after the line: 
`rawFile = importer.execute();`

I have the tiny.mzXML file. It is in the directory:
```
/home/themajor/Desktop/Chemistry_Stuff/msdk/msdk-featuredetection-adap3d/target/test-classes/tiny.mzXML
```

Currently, I have the whole project imported in my Eclipse IDE (version Oxygen 2, release 4.7.2), as shown in the attached image.
screenshot from 2018-02-23 21-30-05

I think there is a problem in importing the class MzXMLFileImportMethod, but none of it shows up on the IDE. Please take a look at this issue at your convenience.

Other than that, can you share a screenshot of the output of the JUnit test on your PC. I would try to decipher as to why we are getting a different output.

Aniket Pradhan

**Comment by asmirn1** [comment]
Here is a screenshot of me running the test
screen shot 2018-02-23 at 11 19 36 am

Does it give you any error message? If not, try to debug the test code and see what happens.

**Comment by Aniket-Pradhan** [comment]
Dear Dr. Alex,

I am not getting any error message (that's the issue). The program simply terminates after line # 55. I will try to resolve this issue.
Until then, regarding the wrong output, I think that the condition on line # 148, in BiGaussian.java, is causing the issue.
```
else if (triplet2.scanListIndex != triplet1.scanListIndex - step) {
                    //triplet2.scanListIndex is not triplet1.scanListIndex-step
                    continue;
                }
```
Since the data is given with scanListIndex values which are not consecutive, sigmaLeft and sigmaRight values should be NaN, since `mu - NaN -> NaN`. But, according to the expected output, we should not get a NaN value. Therefore, most probably, the problem is arising due to the above said code.
Once I get the test code running, I will update you with more details.

Aniket Pradhan

**Comment by Aniket-Pradhan** [comment]
Dear Dr. Alex,

I got the code running. I was unable to do that on my current system, but when I tried it on my other computer, it was working. Probably buggy installation of Java in my previous computer.

Anyways, for the first test case, I saw that we were using the variable `i` which is the `scanListIndex` of Triplet2, to find the `X` value. Since we were not using any other variable to store the scanListIndex value, to simply resolve this issue, we can increment the value of `i`, in the `for` loop. I just made a new pull request for this fix, since my new commit was not showing up in this pull request (because this pull is already merged).

For the second test case, I tried running the test, and realized that the second test should give a NaN value, for both, sigmaRight and sigmaLeft. I also verified this using the original version.

**Comment by asmirn1** [comment]
For the second case test, never mind the original version. We never considered the case like this In the original version. I still think that we should get `sigmaLeft = 2` and `sigmaRight = 6`.

For the second case, I think we should change the line 170 to use `triplet1.scanListIndex` and `triplet2.scanListIndex` instead of `i` and `i - step`. This way, we don't need to increment `i` in the loop. For someone else reading the code, it will be really confusing why you increment `i` in the for-loop, but `i` is never used in that loop.

Do you understand the calculations at line 170? You find x-coordinate of the point with y-coordinate equal to `halfHeight` and lying on the line through the points (i, Y1) and (i-step, Y2).

You can reply in your new pull-request.

**Pull request merged**
